# permissions for end users to view fedclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fedcluster-viewer-role
rules:
- apiGroups:
  - fedtypes.example.com
  resources:
  - fedclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - fedtypes.example.com
  resources:
  - fedclusters/status
  verbs:
  - get
