
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - fedctls.myfed.domain
  resources:
  - fedobjects
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fedctls.myfed.domain
  resources:
  - fedobjects/finalizers
  verbs:
  - update
- apiGroups:
  - fedctls.myfed.domain
  resources:
  - fedobjects/status
  verbs:
  - get
  - patch
  - update
